spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://wikumsurindu1_db_user:u8PYWC7F14mZPYVk@cluster0.mguqwtk.mongodb.net/?appName=Cluster0
server.port=8081

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/api/auth/google/success