spring.application.name=backend
spring.data.mongodb.urispring.data.mongodb.uri=mongodb://localhost:27017/smart_campus
server.port=8081
server.port=8081

spring.data.mongodb.uri=mongodb+srv://nizlochana_db_user:Wikum12345@cluster0.ja8f8hu.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0
